build single pr

diff --git a/.github/workflows/1513-build.yaml b/.github/workflows/1513-build.yaml
--- a/.github/workflows/1513-build.yaml
+++ b/.github/workflows/1513-build.yaml
@@ -20,50 +20,6 @@ concurrency:
   
 jobs:
 
-  # frontend-unit-test:
-
-  #   name: Run Frontend Unit Tests
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 60
-
-  #   steps:
-
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: refs/pull/${{ env.PR_NUMBER }}/head
-
-  #     - name: Fronend Jest coverage report
-  #       uses: ArtiomTr/jest-coverage-report-action@v2.2.1
-  #       continue-on-error: false
-  #       with:
-  #         working-directory: frontend
-  #         test-script: npm run test
-        
-  # backend-unit-test:
-
-  #   name: Run Backend Unit Tests
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 60
-
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: refs/pull/${{ env.PR_NUMBER }}/head
-
-  #     - name: Run coverage report for django tests 
-  #       uses: kuanfandevops/django-test-action@itvr-django-test
-  #       continue-on-error: false
-  #       env:
-  #         MINIO_ENDPOINT: minio:9000
-  #         MINIO_ACCESS_KEY: testtest
-  #         MINIO_SECRET_KEY: testtest
-  #       with:
-  #         settings-dir-path: "backend/api"
-  #         requirements-file: "backend/requirements.txt"
-  #         managepy-dir: backend
-
   database:
 
     name: Start Database
@@ -85,7 +41,7 @@ jobs:
           insecure_skip_tls_verify: true
           namespace: ${{ env.TOOLS_NAMESPACE }}    
 
-      - name: Start Database
+      - name: Setup Database
         shell: bash {0}
         run: |
           cd charts/zeva-spilo
@@ -96,106 +52,107 @@ jobs:
             echo "Installing zeva-spilo-${{ env.PR_NUMBER }}"
             helm install -n ${{ env.DEV_NAMESPACE }} -f ./values-dev-pr.yaml --wait zeva-spilo-${{ env.PR_NUMBER }} .
             echo "zeva-spilo-${{ env.PR_NUMBER }} installed, mounting pvc/db-backups"
-            oc -n ${{ env.DEV_NAMESPACE }} set volume statefulset/zeva-spilo-${{ env.PR_NUMBER }} --add --mount-path=/db-backups -t pvc --claim-name=db-backups --wait=true
+            oc -n ${{ env.DEV_NAMESPACE }} set volume statefulset/zeva-spilo-${{ env.PR_NUMBER }} --add --mount-path=/db-backups -t pvc --claim-name=db-backups
             echo "pvc/db-backups has been mounted"
           fi
 
-  # build:
+  build:
 
-  #   name: Build ZEVA on Openshift
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 60
+    name: Build ZEVA on Openshift
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+    needs: database
 
-  #   steps:
+    steps:
 
-  #     - name: Check out repository
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: refs/pull/${{ env.PR_NUMBER }}/head
+      - name: Check out repository
+        uses: actions/checkout@v3
+        with:
+          ref: refs/pull/${{ env.PR_NUMBER }}/head
 
-  #     - name: Log in to Openshift
-  #       uses: redhat-actions/oc-login@v1.2
-  #       with:
-  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
-  #         openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
-  #         insecure_skip_tls_verify: true
-  #         namespace: ${{ env.TOOLS_NAMESPACE }}
+      - name: Log in to Openshift
+        uses: redhat-actions/oc-login@v1.2
+        with:
+          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
+          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.TOOLS_NAMESPACE }}
 
-  #     - name: Build ZEVA Backend
-  #       run: |
-  #         cd openshift/templates/backend
-  #         oc process -f ./backend-bc.yaml NAME=zeva SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
-  #         oc start-build --wait=true zeva-backend-build-${{ env.PR_NUMBER }}
+      - name: Build ZEVA Backend
+        run: |
+          cd openshift/templates/backend
+          oc process -f ./backend-bc.yaml NAME=zeva SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
+          oc start-build --wait=true zeva-backend-build-${{ env.PR_NUMBER }}
 
-  #     - name: Build ZEVA Frontend
-  #       run: |
-  #         cd openshift/templates/frontend
-  #         oc process -f ./frontend-bc-docker.yaml NAME=zeva SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
-  #         oc start-build --wait=true zeva-frontend-build-${{ env.PR_NUMBER }}
+      - name: Build ZEVA Frontend
+        run: |
+          cd openshift/templates/frontend
+          oc process -f ./frontend-bc-docker.yaml NAME=zeva SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
+          oc start-build --wait=true zeva-frontend-build-${{ env.PR_NUMBER }}
 
-  # deploy-on-dev:
+  deploy-on-dev:
 
-  #   name: Deploy ZEVA on Dev
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 60
-  #   needs: build
+    name: Deploy ZEVA on Dev
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+    needs: build
  
-  #   steps:
+    steps:
 
-      # - name: Please confirm ZEVA database for PR-${{ env.PR_NUMBER }} on Dev has been setup properly
-      #   uses: trstringer/manual-approval@v1.6.0
-      #   with:
-      #     secret: ${{ github.TOKEN }}
-      #     approvers: AlexZorkin,kuanfandevops,tim738745,emi-hi,JulianForeman,jig-patel,vibhiquartech
-      #     minimum-approvals: 1
-      #     issue-title: "Please confirm ZEVA database for PR-${{ env.PR_NUMBER }} on Dev has been setup properly"
-      #     timeout-minutes: 60
+      - name: Please confirm ZEVA database on Dev has been setup properly
+        uses: trstringer/manual-approval@v1.6.0
+        with:
+          secret: ${{ github.TOKEN }}
+          approvers: AlexZorkin,kuanfandevops,tim738745,emi-hi,JulianForeman,jig-patel,vibhiquartech
+          minimum-approvals: 1
+          issue-title: "Please confirm ZEVA database on Dev has been setup properly"
+          timeout-minutes: 60
 
-  #     - name: Check out repository
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: refs/pull/${{ env.PR_NUMBER }}/head
+      - name: Check out repository
+        uses: actions/checkout@v3
+        with:
+          ref: refs/pull/${{ env.PR_NUMBER }}/head
 
-  #     - name: Log in to Openshift
-  #       uses: redhat-actions/oc-login@v1.2
-  #       with:
-  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
-  #         openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
-  #         insecure_skip_tls_verify: true
-  #         namespace: ${{ env.TOOLS_NAMESPACE }}  
+      - name: Log in to Openshift
+        uses: redhat-actions/oc-login@v1.2
+        with:
+          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
+          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.TOOLS_NAMESPACE }}  
       
-  #     - name: Tag Frontend Image from tools to dev
-  #       run: |
-  #         oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-frontend:build-${{ env.VERSION }}-${{ env.PR_NUMBER }} ${{ env.DEV_NAMESPACE }}/zeva-frontend:dev-${{ env.VERSION }}-${{ env.PR_NUMBER }}
-  #         oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-backend:build-${{ env.VERSION }}-${{ env.PR_NUMBER }} ${{ env.DEV_NAMESPACE }}/zeva-backend:dev-${{ env.VERSION }}-${{ env.PR_NUMBER }}
+      - name: Tag Frontend Image from tools to dev
+        run: |
+          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-frontend:build-${{ env.VERSION }}-${{ env.PR_NUMBER }} ${{ env.DEV_NAMESPACE }}/zeva-frontend:dev-${{ env.VERSION }}-${{ env.PR_NUMBER }}
+          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-backend:build-${{ env.VERSION }}-${{ env.PR_NUMBER }} ${{ env.DEV_NAMESPACE }}/zeva-backend:dev-${{ env.VERSION }}-${{ env.PR_NUMBER }}
 
-  #     # helm status will show an error if the helm release doesn't exist. The error will be ignored.
-  #     - name: Deply zeva-frontend on Dev
-  #       shell: bash {0}
-  #       run: |
-  #         cd charts/zeva-apps/charts/zeva-frontend
-  #         helm status -n ${{ env.DEV_NAMESPACE }} zeva-frontend
-  #         if [ $? -eq 0 ]; then
-  #           echo "zeva-frontend release exists already"
-  #           helm upgrade --set frontendImageTagname=dev-${{ env.VERSION }},openshiftLicensePlate=${{ secrets.OPENSHIFT_NAMESPACE_PLATE }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-frontend .
-  #         else
-  #           echo "zeva-frontend release does not exist"
-  #           helm install --set frontendImageTagname=dev-${{ env.VERSION }},openshiftLicensePlate=${{ secrets.OPENSHIFT_NAMESPACE_PLATE }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-frontend .
-  #         fi
+      # helm status will show an error if the helm release doesn't exist. The error will be ignored.
+      - name: Deply zeva-frontend on Dev
+        shell: bash {0}
+        run: |
+          cd charts/zeva-apps/charts/zeva-frontend
+          helm status -n ${{ env.DEV_NAMESPACE }} zeva-frontend-${{ env.PR_NUMBER }}
+          if [ $? -eq 0 ]; then
+            echo "zeva-frontend release exists already"
+            helm upgrade --set frontendImageTagname=dev-${{ env.VERSION }}-${{ env.PR_NUMBER }},openshiftLicensePlate=${{ secrets.OPENSHIFT_NAMESPACE_PLATE }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-frontend-${{ env.PR_NUMBER }} .
+          else
+            echo "zeva-frontend release does not exist"
+            helm install --set frontendImageTagname=dev-${{ env.VERSION }}-${{ env.PR_NUMBER }},openshiftLicensePlate=${{ secrets.OPENSHIFT_NAMESPACE_PLATE }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-frontend-${{ env.PR_NUMBER }} .
+          fi
           
-  #     # helm status will show an error if the helm release doesn't exist. The error will be ignored.
-  #     - name: Deply zeva-backend on Dev
-  #       shell: bash {0}
-  #       run: |
-  #         cd charts/zeva-apps/charts/zeva-backend
-  #         helm status -n ${{ env.DEV_NAMESPACE }} zeva-backend
-  #         if [ $? -eq 0 ]; then
-  #           echo "zeva-backend release exists already"
-  #           helm upgrade --set backendImageTagname=dev-${{ env.VERSION }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-backend .
-  #         else
-  #           echo "zeva-backend release does not exist"
-  #           helm install --set backendImageTagname=dev-${{ env.VERSION }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-backend .
-  #         fi
+      # helm status will show an error if the helm release doesn't exist. The error will be ignored.
+      - name: Deply zeva-backend on Dev
+        shell: bash {0}
+        run: |
+          cd charts/zeva-apps/charts/zeva-backend
+          helm status -n ${{ env.DEV_NAMESPACE }} zeva-backend
+          if [ $? -eq 0 ]; then
+            echo "zeva-backend release exists already"
+            helm upgrade --set backendImageTagname=dev-${{ env.VERSION }}-${{ env.PR_NUMBER }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-backend-${{ env.PR_NUMBER }} .
+          else
+            echo "zeva-backend release does not exist"
+            helm install --set backendImageTagname=dev-${{ env.VERSION }}-${{ env.PR_NUMBER }} -n ${{ env.DEV_NAMESPACE }} -f ./values-dev.yaml zeva-backend-${{ env.PR_NUMBER }} .
+          fi
           
 
       
