update dev-ci before merging

diff --git a/.github/workflows/dev-ci.yaml b/.github/workflows/dev-ci.yaml
--- a/.github/workflows/dev-ci.yaml
+++ b/.github/workflows/dev-ci.yaml
@@ -3,14 +3,11 @@ name: Zeva new-pipeline Dev CI
 # A sample  url in articatory is https://ARTIFACTORY_REGISTRY/artifactory/ARTIFACTORY_REPO/zeva/dev/zeva-backend:1.74.0-20260113220133/
 
 on:
-  # pull_request:
-  #   # Trigger only on PRs targeting the master branch
-  #   branches:
-  #     - master
-  #   types: [opened, synchronize, reopened]
-  push:
-    branches: [devops/artifactory-1.74.0]
-  workflow_dispatch:
+  pull_request:
+    # Trigger only on PRs targeting the master branch
+    branches:
+      - master
+    types: [opened, synchronize, reopened]
 
 env:
   GIT_URL: https://github.com/bcgov/zeva.git
@@ -61,13 +58,13 @@ jobs:
         id: check_pr_title
         run: |
           pr_title="${{ github.event.pull_request.title }}"
-          # echo "Pull Request Title: $pr_title"
+          echo "Pull Request Title: $pr_title"
 
-          # # Check if the title starts with "Tracking"
-          # if [[ "$pr_title" != Tracking* ]]; then
-          #   echo "PR title does not start with 'Tracking'. Exiting..."
-          #   exit 1
-          # fi
+          # Check if the title starts with "Tracking"
+          if [[ "$pr_title" != Tracking* ]]; then
+            echo "PR title does not start with 'Tracking'. Exiting..."
+            exit 1
+          fi
 
   set-pre-release:
     name: Calculate pre-release number
@@ -107,12 +104,12 @@ jobs:
       - id: verify-build-suffix
         run: |
           echo "Validating ${{ env.BUILD_SUFFIX }}"
-          # if [[ "${{ env.BUILD_SUFFIX }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9]{14}$ ]]; then
-          #   echo "Build suffix ${{ env.BUILD_SUFFIX }} format is valid."
-          # else
-          #   echo "Error: Build suffix ${{ env.BUILD_SUFFIX }} format is invalid!"
-          #   exit 1
-          # fi
+          if [[ "${{ env.BUILD_SUFFIX }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9]{14}$ ]]; then
+            echo "Build suffix ${{ env.BUILD_SUFFIX }} format is valid."
+          else
+            echo "Error: Build suffix ${{ env.BUILD_SUFFIX }} format is invalid!"
+            exit 1
+          fi
 
   build-backend:
     name: Build Zeva Backend
@@ -134,29 +131,29 @@ jobs:
           path: /usr/local/bin/oc
           key: oc-cli-${{ runner.os }}
 
-      # - name: Log in to Openshift
-      #   uses: redhat-actions/oc-login@v1.3
-      #   with:
-      #     openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
-      #     openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
-      #     insecure_skip_tls_verify: true
-      #     namespace: ${{ env.TOOLS_NAMESPACE }}
+      - name: Log in to Openshift
+        uses: redhat-actions/oc-login@v1.3
+        with:
+          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
+          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.TOOLS_NAMESPACE }}
 
-      # - name: Build Zeva Backend
-      #   run: |
-      #     echo ${{ env.PRE_RELEASE }}
-      #     echo ${{ env.VERSION }}
-      #     cd openshift/templates/backend
-      #     oc process -f ./backend-bc-docker.yaml NAME=zeva SUFFIX=-${{ env.VERSION }}-${{ env.PRE_RELEASE }} VERSION=${{ env.VERSION }}-${{ env.PRE_RELEASE }} GIT_URL=${{ env.GIT_URL }} GIT_REF=release-${{ env.VERSION }} | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
-      #     # sleep 2s
-      #     # for build in $(oc -n ${{ env.TOOLS_NAMESPACE }} get builds -l buildconfig=zeva-backend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}'); do
-      #     #   echo "canceling $build"
-      #     #   oc -n ${{ env.TOOLS_NAMESPACE }} cancel-build $build
-      #     # done
-      #     # sleep 2s
-      #     oc -n ${{ env.TOOLS_NAMESPACE }} start-build zeva-backend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} --wait=true
-      #     # sleep 2s
-      #     oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-backend:${{ env.VERSION }}-${{ env.PRE_RELEASE }} ${{ env.DEV_NAMESPACE }}/zeva-backend:${{ env.VERSION }}-${{ env.PRE_RELEASE }}
+      - name: Build Zeva Backend
+        run: |
+          echo ${{ env.PRE_RELEASE }}
+          echo ${{ env.VERSION }}
+          cd openshift/templates/backend
+          oc process -f ./backend-bc-docker.yaml NAME=zeva SUFFIX=-${{ env.VERSION }}-${{ env.PRE_RELEASE }} VERSION=${{ env.VERSION }}-${{ env.PRE_RELEASE }} GIT_URL=${{ env.GIT_URL }} GIT_REF=release-${{ env.VERSION }} | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
+          # sleep 2s
+          # for build in $(oc -n ${{ env.TOOLS_NAMESPACE }} get builds -l buildconfig=zeva-backend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}'); do
+          #   echo "canceling $build"
+          #   oc -n ${{ env.TOOLS_NAMESPACE }} cancel-build $build
+          # done
+          # sleep 2s
+          oc -n ${{ env.TOOLS_NAMESPACE }} start-build zeva-backend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} --wait=true
+          # sleep 2s
+          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-backend:${{ env.VERSION }}-${{ env.PRE_RELEASE }} ${{ env.DEV_NAMESPACE }}/zeva-backend:${{ env.VERSION }}-${{ env.PRE_RELEASE }}
 
   build-frontend:
     name: Build Zeva Frontend
@@ -172,33 +169,33 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v4.1.1
 
-      # - name: Restore oc command from Cache
-      #   uses: actions/cache@v4.2.0
-      #   with:
-      #     path: /usr/local/bin/oc
-      #     key: oc-cli-${{ runner.os }}
+      - name: Restore oc command from Cache
+        uses: actions/cache@v4.2.0
+        with:
+          path: /usr/local/bin/oc
+          key: oc-cli-${{ runner.os }}
 
-      # - name: Log in to Openshift
-      #   uses: redhat-actions/oc-login@v1.3
-      #   with:
-      #     openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
-      #     openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
-      #     insecure_skip_tls_verify: true
-      #     namespace: ${{ env.TOOLS_NAMESPACE }}
+      - name: Log in to Openshift
+        uses: redhat-actions/oc-login@v1.3
+        with:
+          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
+          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.TOOLS_NAMESPACE }}
 
-      # - name: Build ZEVA Frontend
-      #   run: |
-      #     cd openshift/templates/frontend
-      #     oc process -f ./frontend-bc-docker.yaml NAME=zeva SUFFIX=-${{ env.VERSION }}-${{ env.PRE_RELEASE }} VERSION=${{ env.VERSION }}-${{ env.PRE_RELEASE }} GIT_URL=${{ env.GIT_URL }} GIT_REF=release-${{ env.VERSION }} | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
-      #     # sleep 2s
-      #     # for build in $(oc -n ${{ env.TOOLS_NAMESPACE }} get builds -l buildconfig=zeva-frontend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}'); do
-      #     #   echo "canceling $build"
-      #     #   oc -n ${{ env.TOOLS_NAMESPACE }} cancel-build $build
-      #     # done
-      #     # sleep 2s
-      #     oc -n ${{ env.TOOLS_NAMESPACE }} start-build zeva-frontend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} --wait=true
-      #     # sleep 2s
-      #     oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-frontend:${{ env.VERSION }}-${{ env.PRE_RELEASE }} ${{ env.DEV_NAMESPACE }}/zeva-frontend:${{ env.VERSION }}-${{ env.PRE_RELEASE }}
+      - name: Build ZEVA Frontend
+        run: |
+          cd openshift/templates/frontend
+          oc process -f ./frontend-bc-docker.yaml NAME=zeva SUFFIX=-${{ env.VERSION }}-${{ env.PRE_RELEASE }} VERSION=${{ env.VERSION }}-${{ env.PRE_RELEASE }} GIT_URL=${{ env.GIT_URL }} GIT_REF=release-${{ env.VERSION }} | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
+          # sleep 2s
+          # for build in $(oc -n ${{ env.TOOLS_NAMESPACE }} get builds -l buildconfig=zeva-frontend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}'); do
+          #   echo "canceling $build"
+          #   oc -n ${{ env.TOOLS_NAMESPACE }} cancel-build $build
+          # done
+          # sleep 2s
+          oc -n ${{ env.TOOLS_NAMESPACE }} start-build zeva-frontend-${{ env.VERSION }}-${{ env.PRE_RELEASE }} --wait=true
+          # sleep 2s
+          oc tag ${{ env.TOOLS_NAMESPACE }}/zeva-frontend:${{ env.VERSION }}-${{ env.PRE_RELEASE }} ${{ env.DEV_NAMESPACE }}/zeva-frontend:${{ env.VERSION }}-${{ env.PRE_RELEASE }}
 
   deploy:
     name: Deploy Zeva on Dev
@@ -218,21 +215,21 @@ jobs:
           ref: main
           ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
 
-      # - name: Update tags
-      #   uses: mikefarah/yq@v4.40.5
-      #   with:
-      #     cmd: |
-      #       yq -i '.frontend.image.tag = "${{ env.VERSION }}-${{ env.PRE_RELEASE }}"' zeva/values-dev.yaml
-      #       yq -i '.backend.image.tag = "${{ env.VERSION }}-${{ env.PRE_RELEASE }}"' zeva/values-dev.yaml
+      - name: Update tags
+        uses: mikefarah/yq@v4.40.5
+        with:
+          cmd: |
+            yq -i '.frontend.image.tag = "${{ env.VERSION }}-${{ env.PRE_RELEASE }}"' zeva/values-dev.yaml
+            yq -i '.backend.image.tag = "${{ env.VERSION }}-${{ env.PRE_RELEASE }}"' zeva/values-dev.yaml
 
-      # - name: GitHub Commit & Push
-      #   shell: bash {0}
-      #   run: |
-      #     git config --global user.email "actions@github.com"
-      #     git config --global user.name "GitHub Actions"
-      #     git add zeva/values-dev.yaml
-      #     git commit -m "Update the image tag to ${{ env.VERSION }}-${{ env.PRE_RELEASE }} on Dev"
-      #     git push
+      - name: GitHub Commit & Push
+        shell: bash {0}
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          git add zeva/values-dev.yaml
+          git commit -m "Update the image tag to ${{ env.VERSION }}-${{ env.PRE_RELEASE }} on Dev"
+          git push
 
   push-to-artifactory:
     name: Push images to Artifactory (${{ matrix.image_stream }})
@@ -247,6 +244,5 @@ jobs:
       env: dev
       app_name: zeva
       image_stream: ${{ matrix.image_stream }}
-      # image_tag: ${{ needs.get-version.outputs.output1 }}-${{ needs.set-pre-release.outputs.output1 }}
-      image_tag: 1.74.0-20260113220122
+      image_tag: ${{ needs.get-version.outputs.output1 }}-${{ needs.set-pre-release.outputs.output1 }}
     secrets: inherit
